platformName: Android
platformVersion: "14"
deviceName: 5baa00a4
appPackage: com.navee.ucaret
appActivity: com.uz.navee.MainActivity
automationName: UiAutomator2
noReset: true
disableWindowAnimation: false
newCommandTimeout: 3600
# 配置信息